services:
  server:
    build:
      context: .
    ports:
      - 4444:4444
    environment:
      CONFIG_PATH: /etc/mqtt-prometheus-adapter/config.yml
    volumes:
      - ./mqtt-prometheus-adapter/:/etc/mqtt-prometheus-adapter/