host: test.mosquitto.org
port: 1883
topics:
  - topic_counter:
    path: test/topic_counter
    type: counter
    description: Demo topic
  - power_state:
    path: test/power_state
    type: gauges
    description: Demo topic