host: test.mosquitto.org
port: 1883
topics:
  - led_state:
    path: test/led_state
    description: Traffic light LEDs
    conversion:
      re_pattern: \d+
      exports:
        - red
        - green
        - blue 
  - power_state:
    path: test/power_state
    description: Demo topic