host: test.mosquitto.org
port: 1883
topics:
  - led_state:
    path: test/led_state
    description: Traffic light LEDs
    conversion:
      re_pattern: '\d+'
      exports:
        - red
        - green
        - blue 
  - display_state:
    path: test/display_state
    description: Display
    conversion:
      re_pattern: "(?<=[',])[a-zA-Z0-9_ ]"
      exports:
        - text_state:
          mapping:
            offen: 1
            geschlossen: 0
  - power_state:
    path: test/power_state
    description: Demo topic
  - reboots:
    path: test/reboot
    description: Device reboots
    type: counter
    filter: '1'
polling:
  interval_ms: 15000
  topics:
    - topic1: "payload1"
    - topic2: "payload2"
log_topic_updates: True